-- public."AspNetRoles" definição

-- Drop table

-- DROP TABLE public."AspNetRoles";

CREATE TABLE public."AspNetRoles" (
	"Id" text NOT NULL,
	"Name" varchar(256) NULL,
	"NormalizedName" varchar(256) NULL,
	"ConcurrencyStamp" text NULL,
	CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);
CREATE UNIQUE INDEX "RoleNameIndex" ON public."AspNetRoles" USING btree ("NormalizedName");


-- public."User" definição

-- Drop table

-- DROP TABLE public."User";

CREATE TABLE public."User" (
	"Id" text NOT NULL,
	"CreatedAt" timestamptz NOT NULL,
	"UpdatedAt" timestamptz NOT NULL,
	"UserName" varchar(256) NULL,
	"NormalizedUserName" varchar(256) NULL,
	"Email" varchar(256) NOT NULL,
	"NormalizedEmail" varchar(256) NULL,
	"EmailConfirmed" bool NOT NULL,
	"PasswordHash" text NULL,
	"SecurityStamp" text NULL,
	"ConcurrencyStamp" text NULL,
	"PhoneNumber" text NULL,
	"PhoneNumberConfirmed" bool NOT NULL,
	"TwoFactorEnabled" bool NOT NULL,
	"LockoutEnd" timestamptz NULL,
	"LockoutEnabled" bool NOT NULL,
	"AccessFailedCount" int4 NOT NULL,
	CONSTRAINT "AK_User_Email" UNIQUE ("Email"),
	CONSTRAINT "PK_User" PRIMARY KEY ("Id")
);
CREATE INDEX "EmailIndex" ON public."User" USING btree ("NormalizedEmail");
CREATE UNIQUE INDEX "IX_User_Email" ON public."User" USING btree ("Email");
CREATE UNIQUE INDEX "UserNameIndex" ON public."User" USING btree ("NormalizedUserName");


-- public."__EFMigrationsHistory" definição

-- Drop table

-- DROP TABLE public."__EFMigrationsHistory";

CREATE TABLE public."__EFMigrationsHistory" (
	"MigrationId" varchar(150) NOT NULL,
	"ProductVersion" varchar(32) NOT NULL,
	CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);


-- public."AccountBalance" definição

-- Drop table

-- DROP TABLE public."AccountBalance";

CREATE TABLE public."AccountBalance" (
	"Id" text NOT NULL,
	"Currency" int4 NOT NULL,
	"UserId" text NOT NULL,
	"Balance" numeric NOT NULL,
	"CreatedAt" timestamptz NOT NULL,
	"UpdatedAt" timestamptz NOT NULL,
	CONSTRAINT "PK_AccountBalance" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_AccountBalance_User_UserId" FOREIGN KEY ("UserId") REFERENCES public."User"("Id") ON DELETE CASCADE
);
CREATE UNIQUE INDEX "IX_AccountBalance_UserId" ON public."AccountBalance" USING btree ("UserId");


-- public."AspNetRoleClaims" definição

-- Drop table

-- DROP TABLE public."AspNetRoleClaims";

CREATE TABLE public."AspNetRoleClaims" (
	"Id" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"RoleId" text NOT NULL,
	"ClaimType" text NULL,
	"ClaimValue" text NULL,
	CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE
);
CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON public."AspNetRoleClaims" USING btree ("RoleId");


-- public."AspNetUserClaims" definição

-- Drop table

-- DROP TABLE public."AspNetUserClaims";

CREATE TABLE public."AspNetUserClaims" (
	"Id" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"UserId" text NOT NULL,
	"ClaimType" text NULL,
	"ClaimValue" text NULL,
	CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_AspNetUserClaims_User_UserId" FOREIGN KEY ("UserId") REFERENCES public."User"("Id") ON DELETE CASCADE
);
CREATE INDEX "IX_AspNetUserClaims_UserId" ON public."AspNetUserClaims" USING btree ("UserId");


-- public."AspNetUserLogins" definição

-- Drop table

-- DROP TABLE public."AspNetUserLogins";

CREATE TABLE public."AspNetUserLogins" (
	"LoginProvider" text NOT NULL,
	"ProviderKey" text NOT NULL,
	"ProviderDisplayName" text NULL,
	"UserId" text NOT NULL,
	CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
	CONSTRAINT "FK_AspNetUserLogins_User_UserId" FOREIGN KEY ("UserId") REFERENCES public."User"("Id") ON DELETE CASCADE
);
CREATE INDEX "IX_AspNetUserLogins_UserId" ON public."AspNetUserLogins" USING btree ("UserId");


-- public."AspNetUserRoles" definição

-- Drop table

-- DROP TABLE public."AspNetUserRoles";

CREATE TABLE public."AspNetUserRoles" (
	"UserId" text NOT NULL,
	"RoleId" text NOT NULL,
	CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
	CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE,
	CONSTRAINT "FK_AspNetUserRoles_User_UserId" FOREIGN KEY ("UserId") REFERENCES public."User"("Id") ON DELETE CASCADE
);
CREATE INDEX "IX_AspNetUserRoles_RoleId" ON public."AspNetUserRoles" USING btree ("RoleId");


-- public."AspNetUserTokens" definição

-- Drop table

-- DROP TABLE public."AspNetUserTokens";

CREATE TABLE public."AspNetUserTokens" (
	"UserId" text NOT NULL,
	"LoginProvider" text NOT NULL,
	"Name" text NOT NULL,
	"Value" text NULL,
	CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
	CONSTRAINT "FK_AspNetUserTokens_User_UserId" FOREIGN KEY ("UserId") REFERENCES public."User"("Id") ON DELETE CASCADE
);


-- public."Bet" definição

-- Drop table

-- DROP TABLE public."Bet";

CREATE TABLE public."Bet" (
	"Id" text NOT NULL,
	"Amount" numeric NOT NULL,
	"Result" int4 NOT NULL,
	"Status" int4 NOT NULL,
	"UserId" text NOT NULL,
	"CreatedAt" timestamptz NOT NULL,
	"UpdatedAt" timestamptz NOT NULL,
	"CanceledAt" timestamptz DEFAULT '-infinity'::timestamp with time zone NOT NULL,
	"FinishAt" timestamptz DEFAULT '-infinity'::timestamp with time zone NOT NULL,
	CONSTRAINT "PK_Bet" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_Bet_User_UserId" FOREIGN KEY ("UserId") REFERENCES public."User"("Id") ON DELETE CASCADE
);
CREATE INDEX "IX_Bet_UserId" ON public."Bet" USING btree ("UserId");


-- public."Transaction" definição

-- Drop table

-- DROP TABLE public."Transaction";

CREATE TABLE public."Transaction" (
	"Id" text NOT NULL,
	"UserId" text NOT NULL,
	"CreatedAt" timestamptz NOT NULL,
	"UpdatedAt" timestamptz NOT NULL,
	"Amount" numeric DEFAULT 0.0 NOT NULL,
	"Currency" text NULL,
	"CurrentBalanceUser" numeric DEFAULT 0.0 NOT NULL,
	"Description" text NULL,
	"TransactionType" text NULL,
	"UserName" text NULL,
	CONSTRAINT "PK_Transaction" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_Transaction_User_UserId" FOREIGN KEY ("UserId") REFERENCES public."User"("Id") ON DELETE CASCADE
);
CREATE INDEX "IX_Transaction_UserId" ON public."Transaction" USING btree ("UserId");